config/routes.rb
Rails.application.routes.draw do
  match 'what_to_watch/display' => 'what_to_watch#display', via: [:get, :post], as: 'what_to_watch'

  # You can have the root of your site routed with "root"
  root 'what_to_watch#index'
end

app/models/flixster_movie.rb
# a Flixster movie people want to see
class FlixsterMovie < OpenStruct
  # attr_accessor :id, :title, :rating, :movietype, :tomatometer, :audiencescore, :theaterReleaseDate, :dvdReleaseDate
  # movietype can be "TopBoxOffice", "Upcoming", "DvdOther", "DvdUpcoming", "DvdNewRelease"

  def eql?(other)
    id == other.id
  end

  def theater_release
    return nil unless theaterReleaseDate
    Time.parse(theaterReleaseDate)
  end

  def dvd_release
    return nil unless dvdReleaseDate
    Time.parse(dvdReleaseDate)
  end

  def format
    if theater_release && theater_release > Time.now
      'upcoming'
    elsif movietype !~ /^Dvd/
      'theater'
    elsif dvd_release && dvd_release < Time.now
      'dvd'
    else
      'unavailable'
    end
  end

  def rating_ish
    tomatometer || 0
  end
end

app/models/flixster_user.rb
class FlixsterUser
  attr_accessor :user_id, :name, :wts_json, :movies

  def initialize(user_id)
    @user_id = user_id
    refresh
  end

  def refresh
    # friends from https://www.flixster.com/api/users/907243067/friends/ -- if authorized
    # ratings from https://www.flixster.com/api/users/790365789/movies/ratings -- anyone
    wts_uri = URI("https://www.flixster.com/api/users/#{user_id}/movies/ratings?scoreTypes=wts")
    result = Net::HTTP.get(wts_uri)
    @wts_json = JSON.parse(result)
    reparse
  end

  def reparse
    user_json = wts_json.first['user']
    @name = "#{user_json['firstName']} #{user_json['lastName']}"
    @movies = wts_json.map {|m| FlixsterMovie.new(m['movie'])}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/what_to_watch_controller.rb
class WhatToWatchController < ApplicationController

  def index
    @user_ids = params[:user_ids] || '907243067'
    @movie_format = 'dvd'
  end

  def display
    user_ids = (params[:user_ids] || '').chomp.split(/,\s*/)
    @user_ids = params[:user_ids]

    redirect_to index unless user_ids.present?

    # format should be 'theater' or 'dvd' or 'upcoming'
    @movie_format = params[:format] || 'dvd'
    num_results_to_display = params[:num_results_to_display] || 10

    users = user_ids.map {|uid| FlixsterUser.new(uid)}

    @best = {}
    users.each do |user|
      # print top n rated movies in category
      @best[user] = user.movies.select {|m| m.format == @movie_format}.sort_by(&:rating_ish).reverse[0..num_results_to_display-1]
    end

    # print top rated movies in common
    if users.length > 1
      in_common = nil
      users.each do |user|
        if in_common.nil?
          in_common = Set.new(user.movies)
        else
          in_common = in_common.intersection(user.movies)
        end
      end
      @best_common = in_common.select {|m| m.format == @movie_format}.sort_by(&:rating_ish).reverse[0..num_results_to_display-1]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/what_to_watch_helper.rb
module WhatToWatchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlixsterPals</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/what_to_watch/_form.html.erb
<%= form_tag what_to_watch_path do %>
    <%= select_tag :format, options_for_select([ "dvd", "theater", "upcoming" ], movie_format || "dvd") %>
    <br /><%= text_field_tag :user_ids, user_ids %>
    <br /><%= submit_tag 'Submit' %>
<% end %>

app/views/what_to_watch/display.html.erb
<p><%= render 'what_to_watch/form', user_ids: @user_ids, movie_format: @movie_format %></p>

<p>Individual best:
<% @best.each do |user, best_movies| %>
    <br /><strong><%= user.name %></strong>
    <% best_movies.each do |movie| %>
      <br /><a href="https://rottentomatoes.com/m/<%= movie.id %>"><%= movie.title %></a>: <%= movie.tomatometer %>% on rotten tomatoes
    <% end %>
<% end %>
</p>

<% if @best_common.present? %>
  <p>Common best:
  <% @best_common.each do |movie| %>
    <br /><a href="https://rottentomatoes.com/m/<%= movie.id %>"><%= movie.title %></a>: <%= movie.tomatometer %>% on rotten tomatoes
  <% end %>
  </p>
<% end %>

app/views/what_to_watch/index.html.erb
<p>Flixster-pals accesses your "want to see" data from <a href="https://www.flixster.com/">Flixster</a> in order to figure out what you want to watch. You'll need to know your user id number, which you can get by visiting your profile page, and the user ids for anyone else you are trying to combine preferences with. Enter those below (comma-separated), and select whether you're looking for a dvd, theater, or upcoming movie to watch! You'll get the top movies you have in common.</p>

<%= render 'what_to_watch/form', user_ids: @user_ids, movie_format: @movie_format %>